# Generated by Django 5.1.4 on 2025-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
